// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQiqVaUm2Fa0oJD6ZfkgmXLEMKCDY1B3o',
    appId: '1:150987439030:web:c2dbdb94a0435a412b1f17',
    messagingSenderId: '150987439030',
    projectId: 'mad-cw6-90e02',
    authDomain: 'mad-cw6-90e02.firebaseapp.com',
    storageBucket: 'mad-cw6-90e02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwa3qS7pfKZjCOD4zPqPl7_WJUL9MjSA',
    appId: '1:150987439030:android:373fda006c47e8fa2b1f17',
    messagingSenderId: '150987439030',
    projectId: 'mad-cw6-90e02',
    storageBucket: 'mad-cw6-90e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-zBYgoSBHLB7a76wwcAGCr8da5J5eQU',
    appId: '1:150987439030:ios:d1b9d1ee7f7b988c2b1f17',
    messagingSenderId: '150987439030',
    projectId: 'mad-cw6-90e02',
    storageBucket: 'mad-cw6-90e02.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-zBYgoSBHLB7a76wwcAGCr8da5J5eQU',
    appId: '1:150987439030:ios:d1b9d1ee7f7b988c2b1f17',
    messagingSenderId: '150987439030',
    projectId: 'mad-cw6-90e02',
    storageBucket: 'mad-cw6-90e02.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQiqVaUm2Fa0oJD6ZfkgmXLEMKCDY1B3o',
    appId: '1:150987439030:web:fe4502033f14d0be2b1f17',
    messagingSenderId: '150987439030',
    projectId: 'mad-cw6-90e02',
    authDomain: 'mad-cw6-90e02.firebaseapp.com',
    storageBucket: 'mad-cw6-90e02.firebasestorage.app',
  );
}
